/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RecoverTrustWalletRouteImport } from './routes/recover.trust-wallet'
import { Route as RecoverSeedPhraseRouteImport } from './routes/recover.seed-phrase'
import { Route as RecoverMetamaskRouteImport } from './routes/recover.metamask'
import { Route as RecoverHardwareWalletRouteImport } from './routes/recover.hardware-wallet'
import { Route as RecoverForgottenPasswordRouteImport } from './routes/recover.forgotten-password'
import { Route as RecoverExchangeLockoutRouteImport } from './routes/recover.exchange-lockout'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedConsoleCasesRouteImport } from './routes/_authenticated/console.cases'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedConsoleCaseIdRouteImport } from './routes/_authenticated/console.case.$id'
import { Route as AuthenticatedConsoleAssessmentIdRouteImport } from './routes/_authenticated/console.assessment.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const RecoverTrustWalletRoute = RecoverTrustWalletRouteImport.update({
  id: '/recover/trust-wallet',
  path: '/recover/trust-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverSeedPhraseRoute = RecoverSeedPhraseRouteImport.update({
  id: '/recover/seed-phrase',
  path: '/recover/seed-phrase',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverMetamaskRoute = RecoverMetamaskRouteImport.update({
  id: '/recover/metamask',
  path: '/recover/metamask',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverHardwareWalletRoute = RecoverHardwareWalletRouteImport.update({
  id: '/recover/hardware-wallet',
  path: '/recover/hardware-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverForgottenPasswordRoute =
  RecoverForgottenPasswordRouteImport.update({
    id: '/recover/forgotten-password',
    path: '/recover/forgotten-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecoverExchangeLockoutRoute = RecoverExchangeLockoutRouteImport.update({
  id: '/recover/exchange-lockout',
  path: '/recover/exchange-lockout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleCasesRoute =
  AuthenticatedConsoleCasesRouteImport.update({
    id: '/cases',
    path: '/cases',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConsoleCaseIdRoute =
  AuthenticatedConsoleCaseIdRouteImport.update({
    id: '/case/$id',
    path: '/case/$id',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleAssessmentIdRoute =
  AuthenticatedConsoleAssessmentIdRouteImport.update({
    id: '/assessment/$id',
    path: '/assessment/$id',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/agent': typeof ApiAgentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/exchange-lockout': typeof RecoverExchangeLockoutRoute
  '/recover/forgotten-password': typeof RecoverForgottenPasswordRoute
  '/recover/hardware-wallet': typeof RecoverHardwareWalletRoute
  '/recover/metamask': typeof RecoverMetamaskRoute
  '/recover/seed-phrase': typeof RecoverSeedPhraseRoute
  '/recover/trust-wallet': typeof RecoverTrustWalletRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/console/cases': typeof AuthenticatedConsoleCasesRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/console/assessment/$id': typeof AuthenticatedConsoleAssessmentIdRoute
  '/console/case/$id': typeof AuthenticatedConsoleCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/agent': typeof ApiAgentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/exchange-lockout': typeof RecoverExchangeLockoutRoute
  '/recover/forgotten-password': typeof RecoverForgottenPasswordRoute
  '/recover/hardware-wallet': typeof RecoverHardwareWalletRoute
  '/recover/metamask': typeof RecoverMetamaskRoute
  '/recover/seed-phrase': typeof RecoverSeedPhraseRoute
  '/recover/trust-wallet': typeof RecoverTrustWalletRoute
  '/blog': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/console/cases': typeof AuthenticatedConsoleCasesRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/console/assessment/$id': typeof AuthenticatedConsoleAssessmentIdRoute
  '/console/case/$id': typeof AuthenticatedConsoleCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/agent': typeof ApiAgentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/exchange-lockout': typeof RecoverExchangeLockoutRoute
  '/recover/forgotten-password': typeof RecoverForgottenPasswordRoute
  '/recover/hardware-wallet': typeof RecoverHardwareWalletRoute
  '/recover/metamask': typeof RecoverMetamaskRoute
  '/recover/seed-phrase': typeof RecoverSeedPhraseRoute
  '/recover/trust-wallet': typeof RecoverTrustWalletRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/console/cases': typeof AuthenticatedConsoleCasesRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/console/assessment/$id': typeof AuthenticatedConsoleAssessmentIdRoute
  '/_authenticated/console/case/$id': typeof AuthenticatedConsoleCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/blog'
    | '/faq'
    | '/forgot-password'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/console'
    | '/dashboard'
    | '/api/agent'
    | '/blog/$slug'
    | '/recover/exchange-lockout'
    | '/recover/forgotten-password'
    | '/recover/hardware-wallet'
    | '/recover/metamask'
    | '/recover/seed-phrase'
    | '/recover/trust-wallet'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/console/cases'
    | '/console/'
    | '/console/assessment/$id'
    | '/console/case/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/faq'
    | '/forgot-password'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/api/agent'
    | '/blog/$slug'
    | '/recover/exchange-lockout'
    | '/recover/forgotten-password'
    | '/recover/hardware-wallet'
    | '/recover/metamask'
    | '/recover/seed-phrase'
    | '/recover/trust-wallet'
    | '/blog'
    | '/.mcp/invoke-tool/$tool'
    | '/console/cases'
    | '/console'
    | '/console/assessment/$id'
    | '/console/case/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/blog'
    | '/faq'
    | '/forgot-password'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/console'
    | '/_authenticated/dashboard'
    | '/api/agent'
    | '/blog/$slug'
    | '/recover/exchange-lockout'
    | '/recover/forgotten-password'
    | '/recover/hardware-wallet'
    | '/recover/metamask'
    | '/recover/seed-phrase'
    | '/recover/trust-wallet'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/console/cases'
    | '/_authenticated/console/'
    | '/_authenticated/console/assessment/$id'
    | '/_authenticated/console/case/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAgentRoute: typeof ApiAgentRoute
  RecoverExchangeLockoutRoute: typeof RecoverExchangeLockoutRoute
  RecoverForgottenPasswordRoute: typeof RecoverForgottenPasswordRoute
  RecoverHardwareWalletRoute: typeof RecoverHardwareWalletRoute
  RecoverMetamaskRoute: typeof RecoverMetamaskRoute
  RecoverSeedPhraseRoute: typeof RecoverSeedPhraseRoute
  RecoverTrustWalletRoute: typeof RecoverTrustWalletRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/recover/trust-wallet': {
      id: '/recover/trust-wallet'
      path: '/recover/trust-wallet'
      fullPath: '/recover/trust-wallet'
      preLoaderRoute: typeof RecoverTrustWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/seed-phrase': {
      id: '/recover/seed-phrase'
      path: '/recover/seed-phrase'
      fullPath: '/recover/seed-phrase'
      preLoaderRoute: typeof RecoverSeedPhraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/metamask': {
      id: '/recover/metamask'
      path: '/recover/metamask'
      fullPath: '/recover/metamask'
      preLoaderRoute: typeof RecoverMetamaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/hardware-wallet': {
      id: '/recover/hardware-wallet'
      path: '/recover/hardware-wallet'
      fullPath: '/recover/hardware-wallet'
      preLoaderRoute: typeof RecoverHardwareWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/forgotten-password': {
      id: '/recover/forgotten-password'
      path: '/recover/forgotten-password'
      fullPath: '/recover/forgotten-password'
      preLoaderRoute: typeof RecoverForgottenPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/exchange-lockout': {
      id: '/recover/exchange-lockout'
      path: '/recover/exchange-lockout'
      fullPath: '/recover/exchange-lockout'
      preLoaderRoute: typeof RecoverExchangeLockoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/cases': {
      id: '/_authenticated/console/cases'
      path: '/cases'
      fullPath: '/console/cases'
      preLoaderRoute: typeof AuthenticatedConsoleCasesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/case/$id': {
      id: '/_authenticated/console/case/$id'
      path: '/case/$id'
      fullPath: '/console/case/$id'
      preLoaderRoute: typeof AuthenticatedConsoleCaseIdRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/assessment/$id': {
      id: '/_authenticated/console/assessment/$id'
      path: '/assessment/$id'
      fullPath: '/console/assessment/$id'
      preLoaderRoute: typeof AuthenticatedConsoleAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
  }
}

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleCasesRoute: typeof AuthenticatedConsoleCasesRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
  AuthenticatedConsoleAssessmentIdRoute: typeof AuthenticatedConsoleAssessmentIdRoute
  AuthenticatedConsoleCaseIdRoute: typeof AuthenticatedConsoleCaseIdRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleCasesRoute: AuthenticatedConsoleCasesRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
  AuthenticatedConsoleAssessmentIdRoute: AuthenticatedConsoleAssessmentIdRoute,
  AuthenticatedConsoleCaseIdRoute: AuthenticatedConsoleCaseIdRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAgentRoute: ApiAgentRoute,
  RecoverExchangeLockoutRoute: RecoverExchangeLockoutRoute,
  RecoverForgottenPasswordRoute: RecoverForgottenPasswordRoute,
  RecoverHardwareWalletRoute: RecoverHardwareWalletRoute,
  RecoverMetamaskRoute: RecoverMetamaskRoute,
  RecoverSeedPhraseRoute: RecoverSeedPhraseRoute,
  RecoverTrustWalletRoute: RecoverTrustWalletRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
